const CWD_NO_ROOT = CWD.substring(ROOT.length);
const Path = require("../../../src/Path");
const {cdBack} = require("../../helpers");

module.exports = {

	"constructor": [
		// [
		// 	path,
		// 	expected_path,
		// 	expected_basename,
		// ],
		[
			"/",
			ROOT,
			"",
		],
		[
			"C:\\",
			IS_UNIX ? `${CWD}${SEP}C:` : "C:\\",
			IS_UNIX ? "C:" : "",
		],
		[
			"some/path/file.xml",
			`${CWD}${SEP}some${SEP}path${SEP}file.xml`,
			"file.xml",
		],
	],

	"normalize": [
		// [path, expected_path],
		[undefined, CWD],
		[{}, `${CWD}${SEP}${{}.toString()}`],
		[new Path(), CWD],
		["", CWD],
		[".", CWD],
		["/", ROOT],
		["/////", ROOT],
		["/\\\\//\\", ROOT],
		["/../..", ROOT],
		["/..\\\\\\..////", ROOT],
		["..////..", cdBack(2)],
		["..C:\\/\\//\\", `${CWD}${SEP}..C:`],
		["../../", cdBack(2)],
		["C:\\", IS_UNIX ? `${CWD}/C:` : "C:\\"],
		["C:\\/\\\\//\\", IS_UNIX ? `${CWD}/C:` : "C:\\"],
		["/C:\\", `${ROOT}C:`],
		["./sub\\..", CWD],
		["/sub1/sub2", `${ROOT}sub1${SEP}sub2`],
		["/sub1/sub2/file.txt", `${ROOT}sub1${SEP}sub2${SEP}file.txt`],
		["C:\\sub1/sub2\\file.txt", IS_UNIX ? `${CWD}/C:/sub1/sub2/file.txt` : `C:\\sub1\\sub2\\file.txt`],
		["sub1/sub2", `${CWD}${SEP}sub1${SEP}sub2`],
		["sub1/sub2/.file", `${CWD}${SEP}sub1${SEP}sub2${SEP}.file`],
		["./sub1/sub2", `${CWD}${SEP}sub1${SEP}sub2`],
		[".\\sub1/sub2/.file", `${CWD}${SEP}sub1${SEP}sub2${SEP}.file`],
		["../../sub1\\sub2\\.file", `${cdBack(2, true)}sub1${SEP}sub2${SEP}.file`],
		["sub1/////sub2////file", `${CWD}${SEP}sub1${SEP}sub2${SEP}file`],
		["///\\\\////.sub1////.sub2\\file\\", `${ROOT}.sub1${SEP}.sub2${SEP}file`],
		["\\sub1\\sub2\\file\\", `${ROOT}sub1${SEP}sub2${SEP}file`],
		["\\sub1//\\//sub2\\file//\\\\\\//", `${ROOT}sub1${SEP}sub2${SEP}file`],
		["sub1/////../../sub2\\file.xml\\", `${cdBack(1, true)}sub2${SEP}file.xml`],
		["sub1\\su.b2\\file\\", `${CWD}${SEP}sub1${SEP}su.b2${SEP}file`],
		["su.b1\\sub2\\file\\\\\\\\", `${CWD}${SEP}su.b1${SEP}sub2${SEP}file`],
		["sub1\\....\\file////", `${CWD}${SEP}sub1${SEP}....${SEP}file`],
		["./su.b1\\sub2\\file\\\\\\\\", `${CWD}${SEP}su.b1${SEP}sub2${SEP}file`],
		[".\\sub1\\....\\file////", `${CWD}${SEP}sub1${SEP}....${SEP}file`],
	],

	"fastForward": [
		// [path, target, expected_path],
		[CWD, CWD, CWD],
		[CWD, "", CWD],
		[CWD, ROOT, CWD],
		[CWD, cdBack(2), CWD],
		[CWD, "/sub1/sub2", `${ROOT}sub1${SEP}sub2${SEP}${CWD_NO_ROOT}`],
		[CWD, "sub1/sub2", `${CWD}${SEP}sub1${SEP}sub2`],
		[CWD, "/sub1/sub2/file.txt", `${ROOT}sub1${SEP}sub2${SEP}file.txt${SEP}${CWD_NO_ROOT}`],
		[CWD, "sub1/sub2/.file", `${CWD}${SEP}sub1${SEP}sub2${SEP}.file`],
		[CWD, cdBack(), CWD],
		[CWD, cdBack(3), CWD],
		["/", CWD, CWD],
		["/", "/", ROOT],
		["/", cdBack(2), cdBack(2)],
		["/", "/sub1/sub2", `${ROOT}sub1${SEP}sub2`],
		["/", "sub1/sub2", `${CWD}${SEP}sub1${SEP}sub2`],
		["/", "/sub1/sub2/file.txt", `${ROOT}sub1${SEP}sub2${SEP}file.txt`],
		["/", "sub1/sub2/.file", `${CWD}${SEP}sub1${SEP}sub2${SEP}.file`],
		["/", cdBack(), cdBack()],
		["/", cdBack(3), cdBack(3)],
		["/sub1/sub2/sub3", CWD, `${CWD}${SEP}sub1${SEP}sub2${SEP}sub3`],
		["/sub1/sub2/sub3", "/", `${ROOT}sub1${SEP}sub2${SEP}sub3`],
		["/sub1/sub2/sub3", cdBack(2), `${cdBack(2, true)}sub1${SEP}sub2${SEP}sub3`],
		["/sub1/sub2/sub3", "/sub1/sub2", `${ROOT}sub1${SEP}sub2${SEP}sub3`],
		["/sub1/sub2/sub3", "sub1/sub2", `${CWD}${SEP}sub1${SEP}sub2${SEP}sub1${SEP}sub2${SEP}sub3`],
		["/sub1/sub2/sub3", "/sub1/sub2/file.txt", `${ROOT}sub1${SEP}sub2${SEP}file.txt${SEP}sub3`],
		["/sub1/sub2/sub3", "sub1/sub2/.file", `${CWD}${SEP}sub1${SEP}sub2${SEP}.file${SEP}sub1${SEP}sub2${SEP}sub3`],
		["/sub1/sub2/sub3", cdBack(), `${cdBack(1, true)}sub1${SEP}sub2${SEP}sub3`],
		["/sub1/sub2/sub3", cdBack(3), `${cdBack(3, true)}sub1${SEP}sub2${SEP}sub3`],
		["sub1/sub2/sub3", CWD, `${CWD}${SEP}sub1${SEP}sub2${SEP}sub3`],
		["sub1/sub2/sub3", "/", `${CWD}${SEP}sub1${SEP}sub2${SEP}sub3`],
		["sub1/sub2/sub3", cdBack(2), `${CWD}${SEP}sub1${SEP}sub2${SEP}sub3`],
		["sub1/sub2/sub3", "/sub1/sub2", `${ROOT}sub1${SEP}sub2${SEP}${CWD_NO_ROOT}${SEP}sub1${SEP}sub2${SEP}sub3`],
		["sub1/sub2/sub3", "sub1/sub2", `${CWD}${SEP}sub1${SEP}sub2${SEP}sub3`],
		[
			"sub1/sub2/sub3",
			"/sub1/sub2/file.txt",
			`${ROOT}sub1${SEP}sub2${SEP}file.txt${SEP}${CWD_NO_ROOT}${SEP}sub1${SEP}sub2${SEP}sub3`,
		],
		["sub1/sub2/sub3", "sub1/sub2/.file", `${CWD}${SEP}sub1${SEP}sub2${SEP}.file${SEP}sub3`],
		["sub1/sub2/sub3", cdBack(), `${CWD}${SEP}sub1${SEP}sub2${SEP}sub3`],
		["sub1/sub2/sub3", cdBack(3), `${CWD}${SEP}sub1${SEP}sub2${SEP}sub3`],
	],

	"publicUrl": {
		"normal_flow": [
			// [path,public_path,expected_url],
			[CWD, CWD, "/"],
			[CWD, "", "/"],
			[CWD, undefined, "/"],
			[CWD, ROOT, `/${CWD_NO_ROOT.replace(/\\/g, "/")}`],
			[CWD, cdBack(2), CWD.replace(cdBack(2, true), "/").replace(/\\/g, "/")],
			[CWD, cdBack(), CWD.replace(cdBack(1, true), "/").replace(/\\/g, "/")],
			[CWD, cdBack(3), CWD.replace(cdBack(3, true), "/").replace(/\\/g, "/")],
			["/", "/", "/"],
			["/sub1/sub2/sub3", "/", "/sub1/sub2/sub3"],
			["/sub1/sub2/sub3", "/sub1/sub2", "/sub3"],
			["./sub1/sub2/sub3", CWD, "/sub1/sub2/sub3"],
			["sub1/sub2/sub3", ROOT, `/${CWD_NO_ROOT.replace(/\\/g, "/")}/sub1/sub2/sub3`],
			["./sub1/sub2/sub3", cdBack(2), `${CWD.replace(cdBack(2, true), "/").replace(/\\/g, "/")}/sub1/sub2/sub3`],
			["sub1/sub2/sub3", "sub1/sub2", "/sub3"],
			["sub1/sub2/sub3", cdBack(), `${CWD.replace(cdBack(1, true), "/").replace(/\\/g, "/")}/sub1/sub2/sub3`],
			["./sub1/sub2/sub3", cdBack(3), `${CWD.replace(cdBack(3, true), "/").replace(/\\/g, "/")}/sub1/sub2/sub3`],
		],

		"throws_error": [
			// [path,public_path],
			[CWD, "/sub1/sub2"],
			[".", `${CWD}/sub1/sub2`],
			[CWD, "/sub1/sub2/file.txt"],
			[CWD, "sub1/sub2/.file"],
			["/", ""],
			["/", `${ROOT}sub1${SEP}sub2`],
			["/", `${CWD}/sub1/sub2`],
			["/", "/sub1/sub2/file.txt"],
			["/", `sub1${SEP}sub2${SEP}.file`],
			["/sub1/sub2/sub3", CWD],
			["/sub1/sub2/sub3", `${CWD}/sub1/sub2`],
			["/sub1/sub2/sub3", "/sub1/sub2/file.txt"],
			["/sub1/sub2/sub3", `${CWD}/sub1/sub2/.file`],
			[`${CWD}/sub1/sub2/sub3`, "/sub1/sub2"],
			[`${CWD}/sub1/sub2/sub3`, "/sub1/sub2/file.txt"],
			["./sub1/sub2/sub3", `${CWD}/sub1/sub2/.file`],
		],
	},

};
